name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: |
            8
            17
          cache: sbt
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Build jar files
        run: sbt assembly
      - name: Upload jar files
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: |
            1-12/target/build/**.jar
            1-18/target/build/**.jar
